---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update the distro
      apt: 
        update_cache: yes
        upgrade: full
      register: apt_action
      retries: 4
      delay: 1
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

